# Generated by Django 5.2.2 on 2025-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
