# Generated by Django 5.2.2 on 2025-06-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_image_event_image_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image_change',
            new_name='image',
        ),
    ]
