# Generated by Django 5.2.2 on 2025-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
